/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author estudiante
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonUnoEntreX2 = new javax.swing.JButton();
        pantalla = new javax.swing.JTextField();
        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        Botonmasmenos = new javax.swing.JButton();
        Botoncero = new javax.swing.JButton();
        Botonc = new javax.swing.JButton();
        Botoncoma1 = new javax.swing.JButton();
        BotonRaiz = new javax.swing.JButton();
        Botonigual1 = new javax.swing.JButton();
        Botonresta = new javax.swing.JButton();
        Botonmultipli = new javax.swing.JButton();
        Botondivision = new javax.swing.JButton();
        Botonsuma1 = new javax.swing.JButton();
        Botonx3 = new javax.swing.JButton();
        BotonUnoEntreX1 = new javax.swing.JButton();
        BotonPorcentaje = new javax.swing.JButton();
        Botonx4 = new javax.swing.JButton();
        BotonBorrar1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Botonbin = new javax.swing.JButton();
        Botondec = new javax.swing.JButton();

        BotonUnoEntreX2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonUnoEntreX2.setText("1/x");
        BotonUnoEntreX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUnoEntreX2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla.setText("0");
        pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaActionPerformed(evt);
            }
        });

        Boton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton1.setText("1");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        Boton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton2.setText("2");
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });

        Boton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton3.setText("3");
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });

        Boton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton4.setText("4");
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });

        Boton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton5.setText("5");
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });

        Boton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton6.setText("6");
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });

        Boton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton7.setText("7");
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });

        Boton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton8.setText("8");
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });

        Boton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Boton9.setText("9");
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });

        Botonmasmenos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Botonmasmenos.setText("+/-");
        Botonmasmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonmasmenosActionPerformed(evt);
            }
        });

        Botoncero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botoncero.setText("0");
        Botoncero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonceroActionPerformed(evt);
            }
        });

        Botonc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botonc.setText("c");
        Botonc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoncActionPerformed(evt);
            }
        });

        Botoncoma1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botoncoma1.setText(",");
        Botoncoma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botoncoma1ActionPerformed(evt);
            }
        });

        BotonRaiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonRaiz.setText("sqrt");
        BotonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRaizActionPerformed(evt);
            }
        });

        Botonigual1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botonigual1.setText("=");
        Botonigual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botonigual1ActionPerformed(evt);
            }
        });

        Botonresta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botonresta.setText("-");
        Botonresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonrestaActionPerformed(evt);
            }
        });

        Botonmultipli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botonmultipli.setText("*");
        Botonmultipli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonmultipliActionPerformed(evt);
            }
        });

        Botondivision.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botondivision.setText("/");
        Botondivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotondivisionActionPerformed(evt);
            }
        });

        Botonsuma1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botonsuma1.setText("+");
        Botonsuma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botonsuma1ActionPerformed(evt);
            }
        });

        Botonx3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botonx3.setText("x^3");
        Botonx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botonx3ActionPerformed(evt);
            }
        });

        BotonUnoEntreX1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonUnoEntreX1.setText("1/x");
        BotonUnoEntreX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUnoEntreX1ActionPerformed(evt);
            }
        });

        BotonPorcentaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonPorcentaje.setText("%");
        BotonPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPorcentajeActionPerformed(evt);
            }
        });

        Botonx4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botonx4.setText("x^2");
        Botonx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botonx4ActionPerformed(evt);
            }
        });

        BotonBorrar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonBorrar1.setText("<-");
        BotonBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrar1ActionPerformed(evt);
            }
        });

        jTextField1.setText("Designed and programmed by: Buriticá Ricardo");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Botonbin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botonbin.setText("bin");
        Botonbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonbinActionPerformed(evt);
            }
        });

        Botondec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Botondec.setText("dec");
        Botondec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotondecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Botonx3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonUnoEntreX1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonPorcentaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Botonx4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotonBorrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Boton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Boton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Boton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Botonmasmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Boton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Boton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Boton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Botoncero, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(BotonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Boton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Boton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Boton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Botoncoma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Botonc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Botonigual1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Botonsuma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Botonresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Botonmultipli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Botondivision, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Botonbin)
                    .addComponent(Botondec))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botonmultipli, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botonbin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botonx4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botonresta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Botonmasmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botoncero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botoncoma1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botonx3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botonsuma1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botonc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonUnoEntreX1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botonigual1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botondivision, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Botondec, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantallaActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed

// TODO add your handling code here:
        if (pantalla.getText().equals("0")) { //verificar que dos string sean iguales
            pantalla.setText("");
        }
        m = pantalla.getText() + "1";
        pantalla.setText(m);

    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().equals("0")) {
            pantalla.setText("");
        }
        m = pantalla.getText() + "2";
        pantalla.setText(m);
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().equals("0")) {
            pantalla.setText("");
        }
        m = pantalla.getText() + "3";
        pantalla.setText(m);
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().equals("0")) {
            pantalla.setText("");
        }
        m = pantalla.getText() + "4";
        pantalla.setText(m);
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().equals("0")) {
            pantalla.setText("");
        }
        m = pantalla.getText() + "5";
        pantalla.setText(m);
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().equals("0")) {
            pantalla.setText("");
        }
        m = pantalla.getText() + "6";
        pantalla.setText(m);
    }//GEN-LAST:event_Boton6ActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().equals("0")) {
            pantalla.setText("");
        }
        m = pantalla.getText() + "7";
        pantalla.setText(m);
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().equals("0")) {
            pantalla.setText("");
        }
        m = pantalla.getText() + "8";
        pantalla.setText(m);
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().equals("0")) {
            pantalla.setText("");
        }
        m = pantalla.getText() + "9";
        pantalla.setText(m);
    }//GEN-LAST:event_Boton9ActionPerformed

    private void BotonmasmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonmasmenosActionPerformed
        // TODO add your handling code here:
        double valor = Double.parseDouble(pantalla.getText());
        int valorint = (int) valor;
        double restados = valor - valorint;
        if (restados == 0) {
            valorint = valorint * -1;
            pantalla.setText(String.valueOf(valorint));
        } else {
            valor = valor * -1;
            pantalla.setText(String.valueOf(valor));
        }


    }//GEN-LAST:event_BotonmasmenosActionPerformed

    private void BotonceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonceroActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().equals("0")) {
            pantalla.setText("");
        } else {
            m = pantalla.getText() + "0";
        }
        pantalla.setText(m);
    }//GEN-LAST:event_BotonceroActionPerformed

    private void BotoncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoncActionPerformed
        // TODO add your handling code here:

        pantalla.setText("0");

    }//GEN-LAST:event_BotoncActionPerformed

    private void Botoncoma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botoncoma1ActionPerformed
        // TODO add your handling code here:
        String cadena;
        cadena = pantalla.getText();

        if (cadena.length() <= 0) {
            pantalla.setText("0.");

        } else {
            if (!existe_punto(pantalla.getText())) {
                pantalla.setText(pantalla.getText() + ".");

            }
        }
    }//GEN-LAST:event_Botoncoma1ActionPerformed

    private void BotonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRaizActionPerformed
        // TODO add your handling code here:
        memoria = Double.parseDouble(pantalla.getText());
        op = "sqrt";
        pantalla.setText(m);
    }//GEN-LAST:event_BotonRaizActionPerformed

    private void Botonigual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botonigual1ActionPerformed
        // TODO add your handling code here:
        double res = 0;
        int resint = (int) res;
        int res_b = 0;

        //equals se usa para comparar dos string
        if (op.equals("+")) {
            res = memoria + Double.parseDouble(pantalla.getText());

            resint = (int) res;
        } else if (op.equals("-")) {
            res = memoria - Double.parseDouble(pantalla.getText());

            resint = (int) res;
        } else if (op.equals("*")) {
            res = memoria * Double.parseDouble(pantalla.getText());
            resint = (int) res;
        } else if (op.equals("/")) {
            res = memoria / Double.parseDouble(pantalla.getText());
            resint = (int) res;
        } else if (op.equals("sqrt")) {
            res = Math.sqrt(Double.parseDouble(pantalla.getText()));
            resint = (int) res;
        } else if (op.equals("1/x")) {
            res = 1 / (Double.parseDouble(pantalla.getText()));
            resint = (int) res;
        } else if (op.equals("x^3")) {
            res = Math.pow(Double.parseDouble(pantalla.getText()), 3);
            resint = (int) res;
        } else if (op.equals("x^2")) {
            res = Math.pow(Double.parseDouble(pantalla.getText()), 2);
            resint = (int) res;
        } else if (op.equals("%")) {
            res = (memoria / 100) * Double.parseDouble(pantalla.getText());

            resint = (int) res;
        }

        //se usa para sacar la parte entera del numero en double
        long iPart = (long) res;
        double restpart = res - iPart;
        if (restpart != 0) {
            pantalla.setText(String.valueOf(res));
        } else {
            pantalla.setText(String.valueOf(resint));
        }


    }//GEN-LAST:event_Botonigual1ActionPerformed

    private void BotonrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonrestaActionPerformed
        // TODO add your handling code here:
        memoria = Double.parseDouble(pantalla.getText());
        op = "-";
        m = "";
        pantalla.setText(m);
    }//GEN-LAST:event_BotonrestaActionPerformed

    private void BotonmultipliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonmultipliActionPerformed
        // TODO add your handling code here:
        memoria = Double.parseDouble(pantalla.getText());
        op = "*";
        m = "";
        pantalla.setText(m);
    }//GEN-LAST:event_BotonmultipliActionPerformed

    private void BotondivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotondivisionActionPerformed
        // TODO add your handling code here:
        memoria = Double.parseDouble(pantalla.getText());
        op = "/";
        m = "";
        pantalla.setText(m);
    }//GEN-LAST:event_BotondivisionActionPerformed

    private void Botonsuma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botonsuma1ActionPerformed
        // TODO add your handling code here:
        memoria = Double.parseDouble(pantalla.getText());
        op = "+";
        m = "";
        pantalla.setText(m);
    }//GEN-LAST:event_Botonsuma1ActionPerformed

    private void Botonx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botonx3ActionPerformed
        // TODO add your handling code here:
        memoria = Double.parseDouble(pantalla.getText());
        op = "x^3";
        pantalla.setText(m);
    }//GEN-LAST:event_Botonx3ActionPerformed

    private void BotonUnoEntreX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUnoEntreX1ActionPerformed
        // TODO add your handling code here:
        memoria = Double.parseDouble(pantalla.getText());
        op = "1/x";
        pantalla.setText(m);
    }//GEN-LAST:event_BotonUnoEntreX1ActionPerformed

    private void BotonPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPorcentajeActionPerformed
        // TODO add your handling code here:
        memoria = Double.parseDouble(pantalla.getText());
        op = "%";
        m = "";
        pantalla.setText(m);
    }//GEN-LAST:event_BotonPorcentajeActionPerformed

    private void Botonx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botonx4ActionPerformed
        // TODO add your handling code here:
        memoria = Double.parseDouble(pantalla.getText());
        op = "x^2";
        pantalla.setText(m);
    }//GEN-LAST:event_Botonx4ActionPerformed

    private void BotonBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrar1ActionPerformed
        // TODO add your handling code here:
        if (pantalla.getText().length() != 0) {
            pantalla.setText(pantalla.getText().substring(0, pantalla.getText().length() - 1));
        }
    }//GEN-LAST:event_BotonBorrar1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BotonUnoEntreX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUnoEntreX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonUnoEntreX2ActionPerformed

    private void BotonbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonbinActionPerformed
        // TODO add your handling code here:
        String binario = "";
        double res = 0;
        op = "bin";
        pantalla.setText(m);
        if (op.equals("bin")) {
            res = Double.parseDouble(pantalla.getText());
            if (res > 0) {
                while (res > 0) {
                    if (res % 2 == 0) {
                        binario = "0" + binario;
                    } else {
                        binario = "1" + binario;
                    }
                    res = (int) res / 2;
                }
            } else if (res == 0) {
                binario = "0";

            } else {
                binario = "No se pudo convertir el numero. Ingrese solo numeros positivos";
            }
            pantalla.setText(binario);
        }
    }//GEN-LAST:event_BotonbinActionPerformed

    private void BotondecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotondecActionPerformed
        // TODO add your handling code here:
        op = "dec";
        pantalla.setText(m);
        if (op.equals("dec")) {
        int res;
        res = Integer.parseInt(pantalla.getText());
        binaryToDecimal(res);
        pantalla.setText(String.valueOf(res));
        }
        
    }//GEN-LAST:event_BotondecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    String op = "n";
    String m = "";
    double memoria = 0;

//Metodo para verificar que si hay un punto en la pantalla
    public static boolean existe_punto(String cadena) {
        boolean resultado;
        resultado = false;

        for (int i = 0; i < cadena.length(); i++) {
            if (cadena.substring(i, i + 1).equals(".")) {
                resultado = true;
                break;

            }

        }
        return resultado;

    }

    public static int binaryToDecimal(int number) {
        int decimal = 0;
        int binary = number;
        int power = 0;
        
        while (binary != 0) {

            int lastDigit = binary % 10;

            decimal += lastDigit * Math.pow(2, power);

            power++;

            binary = binary / 10;

        }

        return decimal;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonBorrar1;
    private javax.swing.JButton BotonPorcentaje;
    private javax.swing.JButton BotonRaiz;
    private javax.swing.JButton BotonUnoEntreX1;
    private javax.swing.JButton BotonUnoEntreX2;
    private javax.swing.JButton Botonbin;
    private javax.swing.JButton Botonc;
    private javax.swing.JButton Botoncero;
    private javax.swing.JButton Botoncoma1;
    private javax.swing.JButton Botondec;
    private javax.swing.JButton Botondivision;
    private javax.swing.JButton Botonigual1;
    private javax.swing.JButton Botonmasmenos;
    private javax.swing.JButton Botonmultipli;
    private javax.swing.JButton Botonresta;
    private javax.swing.JButton Botonsuma1;
    private javax.swing.JButton Botonx3;
    private javax.swing.JButton Botonx4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pantalla;
    // End of variables declaration//GEN-END:variables
}
